---
site_name: The FOSS for Families Guide
site_description: The FOSS for Families Guide
repo_url: https://github.com/technowax/the-foss-for-families-guide
repo_name: technowax/the-foss-for-families-guide
edit_uri: edit/main/docs
strict: true

markdown_extensions:
  - codehilite
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - toc:
      permalink: true

theme:
  name: material
  logo: faridoon.png
  favicon: faridoon.png
  language: en
  include_search_page: true
  search_index_only: true
  palette:
    primary: deep purple
  features:
    - search.suggest
    - search.highlight
    - search.share
    - content.code.copy
    - content.action.edit
  icon:
    repo: fontawesome/brands/github


plugins:
  - search:
  - minify:
      minify_html: true
  - tags:

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/jamesread/faridoon

    - icon: fontawesome/brands/mastodon
      link: https://mastodon.social/@jamesread

    - icon: fontawesome/brands/x-twitter
      link: https://twitter.com/jamesreadtweets

nav:
  - Introduction: index.md
  - "Servers & Hardware": servers-and-hardware/index.md
  - "Media & Entertainment": media-and-entertainment/index.md
  - "Home Automation": home-automation/index.md
  - "Out of the House": out-of-the-house/index.md
